server:
  port: 8084

spring:
  config:
    import: "optional:configserver:http://localhost:8085"
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: ratingservice
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
        - id: hotelservice
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
        - id: AUTHSERVICE
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**

      discovery:
        locator:
          enabled: true

#okta:
#  oauth2:
#    issuer: https://dev-96942190.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oak980179HDv32kA5d7
#    client-secret: AHYA46H9CAPb6qsYD_xkwggJtUa0wRoWosyO_G2dvhvj5g8g3P7dsR-PPjwj-pST
#    scopes: openid, profile, email, offline_access
      

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
