server:
  port: 8084

spring:
  config:
    import: "optional:configserver:http://localhost:8085"
  application:
    name: APIGATEWAY
  cloud:
    gateway:
      routes:
        - id: userservice
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
        - id: ratingservice
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
        - id: hotelservice
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**

      discovery:
        locator:
          enabled: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
