server:
  port: 8084

spring:
  config:
    import: "optional:configserver:http://localhost:8085"
  application:
    name: APIGATEWAY
    
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/USERSERVICE/(?<remaining>.*), /${remaining}
          
        - id: rating-service
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/ratings/**
          filters:
            - RewritePath=/RATINGSERVICE/(?<remaining>.*), /${remaining}
            - name: Jwt  # This will apply Jwt filter to the ratings route only
          
        - id: hotel-service
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotels/**
          filters:
            - RewritePath=/HOTELSERVICE/(?<remaining>.*), /${remaining}
          
        - id: auth-service
          uri: lb://AUTHSERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/AUTHSERVICE/(?<remaining>.*), /${remaining}
            
      discovery:
        locator:
          enabled: true

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    
#okta:
#  oauth2:
#    issuer: https://dev-96942190.okta.com/oauth2/default
#    audience: api://default
#    client-id: 0oak980179HDv32kA5d7
#    client-secret: AHYA46H9CAPb6qsYD_xkwggJtUa0wRoWosyO_G2dvhvj5g8g3P7dsR-PPjwj-pST
#    scopes: openid, profile, email, offline_access
      

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
