server:
  port: 8081

spring:
  config:
    import: "configserver:http://localhost:8085"
    
  application:
    name: UserService
  datasource:
    url: jdbc:mysql://localhost:3306/usermicroservices
    username: dbroot
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka
